apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service       # Use .Release.Name for dynamic name
spec:
  selector:
    app: {{ .Release.Name }}-app          # Use .Release.Name for labels
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }}      # Use .Values.servicePort for the port value
      targetPort: {{ .Values.service.targetPort }} # Use .Values.targetPort for the targetPort value
      nodePort: {{ .Values.service.nodePort }}     # Use .Values.nodePort for NodePort value
  type: {{ .Values.service.typePort }}
