name: Continuous Integration/Continuous Testing/Continuous Deployment

 

on:
  push:
    branches:
      - main

 

jobs:
  build:
    runs-on: ubuntu-22.04

 

    steps:
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Checkout Code
        uses: actions/checkout@v2

 

      - name: Run Unit Tests
        run: |
          cd Math
          mvn '-Dtest=rafaeldireito.com.math.unit_tests.*Tests' test

 

      - name: Run API End-to-End Tests
        run: |
          cd Math
          mvn '-Dtest=rafaeldireito.com.math.end_to_end_tests.api.*Tests' test

 

      - name: Run Web UI End-to-End Tests
        run: |
          cd Math
          mvn '-Dtest=rafaeldireito.com.math.end_to_end_tests.ui.*Tests' test

 

      - name: Package Application
        run: |
          cd Math
          mvn clean package -DskipTests=true  # Add -DskipTests=true to skip tests

 

      - name: Build Docker Image
        run: |
          docker build -t f1regg/mathimage -f Dockerfile .

 

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.f1REgg2501 }}" | docker login -u f1regg --password-stdin

 

      - name: Push Docker Image
        run: |
          docker push f1regg/mathimage:latest
