  GNU nano 6.2                                                                main.yaml                                                                         

      - name: Checkout Code
        uses: actions/checkout@v2

 

      - name: Static Code Analysis
        run: |
          cd Math
          mvn checkstyle:check

 

      - name: Run Unit Tests
        run: |
          cd Math
          mvn '-Dtest=rafaeldireito.com.math.unit_tests.*Tests' test

 

      - name: Run API End-to-End Tests
        run: |
          cd Math
          mvn '-Dtest=rafaeldireito.com.math.end_to_end_tests.api.*Tests' test

 

      - name: Run Web UI End-to-End Tests
        run: |
          cd Math
          mvn '-Dtest=rafaeldireito.com.math.end_to_end_tests.ui.*Tests' test
